config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :ques do
    collection do
      get :search_names
    end

    member do
      patch :help_student
      patch :resolve_student
      patch :try_helping_student
    end
  end

end

app/models/que.rb
class Que < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  before_create :send_que_email

  def send_que_email
    QueMailer.new_que_email(self).deliver
  end

  # What this is saying:
  # Let's find all of the names that contain ?
  # scope :funk_names, -> { where("name like ?", "%Funk%") }

  scope :search_names, -> search { where( "name like ?", "%#{search}%") }

  # Que.all.search_names("Adolf")

  # @hospital = Hospital.find 
  # @patients = hospital.patients
  # @patients.search_names("Adolf")

  # def self.search_names(search)
  #   where("name like ?", "%#{search}%")
  # end

  def display_name
    "Mr. #{name}"
  end

  include Workflow
  workflow do
    state :new do
      event :nick_visit, transitions_to: :in_progress
    end
    state :in_progress do
      event :nick_leave, transitions_to: :completed
      event :nick_tried_helping, transitions_to: :still_confused
    end
    state :still_confused do
      event :nick_visit, transitions_to: :in_progress
    end
    state :completed
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # respond_to :html

  def index
    @people_in_que = Que.where.not(workflow_state: "completed")
    @people_who_are_inifintely_smarter_then_they_were_before_but_still_cant_spell = Que.where(workflow_state: "completed")
    # respond_with @people_in_que
  end
end

app/controllers/ques_controller.rb
class QuesController < ApplicationController
  respond_to :html, :json
  layout 'new_queue'
  # def index
  #   # GET
  #   # List of data
  #   # Replaced by our home index CURRENTLY
  # end
  def index
    @ques = Que.all
    respond_to do |format|
      format.json { render json: @ques }
    end
  end

  def show
    # GET
    # Shows an individual object
    @que = Que.find params[:id]
  end

  def new
    # GET
    # Brings you to the new page
    @que = Que.new
    respond_with @queue
  end

  def create
    # POST
    # Creates the data
    @que = Que.new que_params
    success = @que.save
    if success == true
      flash[:notice] = "You have successfully entered le Que."
      redirect_to root_path
    else
      flash[:error] = "You need to enter more information before entering le Que."
      render :new
    end
  end

  def edit
    # GET
    # Brings you to the edit page
    @que = Que.find params[:id]
  end

  def update
    # PUT/PATCH
    # Updates existing data
    @que = Que.find params[:id]
    success = @que.update_attributes que_params
    if success == true
      flash[:notice] = "You have successfully updated le Que."
      redirect_to root_path
    else
      flash[:error] = "You need to enter more information before editing your Que."
      render :edit
    end
  end

  def destroy
    # DELETE
    # Deletes stuff
    @que = Que.find params[:id]
    @que.delete
    redirect_to root_path
  end

  def help_student
    @que = Que.find params[:id]
    @que.nick_visit!

    respond_to do |format|
      # dataType: "script"
      # this is format.js in our controller
      format.js
    end
  end

  def resolve_student
    @que = Que.find params[:id]
    @que.nick_leave!
    respond_to do |format|
      format.js
    end
  end

  def try_helping_student
    @que = Que.find params[:id]
    @que.nick_tried_helping!
    respond_to do |format|
      format.js
    end
  end

  def search_names
    @search_names = Que.search_names params[:q]
  end
  
  private
    def que_params
      params.require(:que).permit(:name, :email, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ques_helper.rb
module QuesHelper
  def display_links(person)
    if person.workflow_state == 'new'
      link_to "Help This Student", 'javascript:void(0)', class: "help_this_student change_workflow", que_url: help_student_que_path(person)
    elsif person.workflow_state == 'in_progress'
      a = link_to "Resolve", 'javascript:void(0);', class: "resolve_student change_workflow", que_url: resolve_student_que_path(person)
      a += ' | '
      a += link_to "Still Confused", 'javascript:void(0);',class: "still_confused change_workflow", que_url: try_helping_student_que_path(person)
      a
    elsif person.workflow_state == 'still_confused'
      link_to "Re Help", 'javascript:void(0);', class: "re_help change_workflow", que_url: help_student_que_path(person)
    end
  end
end

app/views/home/index.html.haml
= link_to "Funk Names", search_names_ques_path
= render 'ques/search'
= t(:marketing_content)
%h4 These Guys are in Queue
= link_to "I need help!", new_que_path
= link_to "Hide Students", "javascript:void(0);", class: "hide_students"
= link_to "Show Students", "javascript:void(0);", class: "show_students"
= link_to "Remove Students", "javascript:void(0);", class: "remove_students"
%ul.students
  - @people_in_que.each do |person|
    = render 'ques/student', student: person

%h4 People Resolved

.resolved_students
  - @people_who_are_inifintely_smarter_then_they_were_before_but_still_cant_spell.each do |person|
    = person.name
    helped at
    = person.updated_at.strftime("%l:%M%p")
    %br


%a.do_something_cool{href: "javascript:void(0);"} Cool Stuff

app/views/layouts/_error_messages.html.haml
- object.errors.messages.each do |k, v|
  - v.each do |message|
    = k.capitalize
    = message
    %br

/ In HAML
/ = is display
/ - is ruby logic that you don't want displayed
/ % is for HTMl tags
/ %div.blue_background
/ .blue_background

app/views/layouts/_flash.html.haml
- if flash[:notice]
  .notice= flash[:notice]
- elsif flash[:error]
  .error= flash[:error]

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Class 12
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %h1= t(:header)
    = render 'layouts/flash'
    = yield

app/views/layouts/new_queue.html.haml
!!!
%html
  %head
    %title Class 12
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %h1 This is a separate layout
    = yield

app/views/ques/_form.html.haml
= form_for @que, html: { multipart: true } do |f|
  = render 'layouts/error_messages', object: @que
  = f.label :name
  = f.text_field :name, placeholder: t('activerecord.attributes.que.name')
  %br
  = f.label :email
  = f.text_field :email, placeholder: t('activerecord.attributes.que.email')
  %br
  = f.file_field :image
  %br
    = f.submit
= link_to "Home", root_path

app/views/ques/_search.html.haml
= form_tag search_names_ques_path, method: :get do
  = text_field_tag "q", "", placeholder: "Search..."
  = submit_tag "Search"

/ Form for
/ = form_for @patient do |f|
/   = text_field :name
/   Form for will turn the above into this:
/   patient[name]
/   this will come across via your controller:
/   { patient: { name: "Jim" } }
/   params[:patient]

app/views/ques/_student.html.haml
%li{ class: "#{student.workflow_state} student student_#{student.id}"}
  = student.name
  (#{student.workflow_state})
  = student.created_at.strftime("%l:%M%p")
  = link_to "Show", que_path(student)
  |
  = link_to "Edit", edit_que_path(student)
  |
  = link_to "Delete", que_path(student), method: :delete
  |
  = display_links(student)
  |
  = link_to "Remove From List", "javascript:void(0);", class: "remove_student_from_list"

app/views/ques/edit.html.haml
%h4 Edit Some Person
= render 'form'

app/views/ques/help_student.js.erb
console.log("<%= @que.inspect %>")
$("li.student_" + "<%= @que.id %>").replaceWith(
  "<%= escape_javascript(render(partial: 'ques/student', locals: { student: @que})) %>"
)

app/views/ques/new.html.erb
<h4>New Que</h4>
<%= render 'form' %>

app/views/ques/resolve_student.js.haml
console.log("#{@que.inspect}")
$("li.student_#{ @que.id }").remove()
$("div.resolved_students").append(
"#{@que.name} helped at #{ @que.updated_at.strftime('%l:%M%p') }<br>"
);

app/views/ques/search_names.html.haml
%h4 Search

%ul
  - @search_names.each do |search_name|
    = render 'ques/student', student: search_name
  

app/views/ques/show.html.haml
%h4 This is a person in que

= @que.name
got into que
= @que.created_at.strftime("%l:%M%p")
%br
= image_tag @que.image.url
%br
= link_to "Home", root_path

app/views/ques/try_helping_student.js.erb
console.log("<%= @que.inspect %>")
$("li.student_" + "<%= @que.id %>").replaceWith(
  "<%= escape_javascript(render(partial: 'ques/student', locals: { student: @que})) %>"
)